## Configuration Nginx
web:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /var/www/docker/nginx:/etc/nginx/conf.d
    - /var/www:/var/www/local.dev
  links:
    - php5.6:php5.6
    - php7.0:php7.0
    - php7.1:php7.1
    - php7.2:php7.2
    - maildev:maildev

## Configuration PHP 5.6
php5.6:
  build: php5.6
  restart: always
  volumes:
    - /var/www:/var/www/local.dev
    - /var/www/docker/php.ini:/usr/local/etc/php/php.ini
  links:
    - db:db

## Configuration PHP 7.0
php7.0:
  build: php7.0
  restart: always
  volumes:
    - /var/www:/var/www/local.dev
    - /var/www/docker/php.ini:/usr/local/etc/php/php.ini
  links:
    - db:db

## Configuration PHP 7.1
php7.1:
  build: php7.1
  restart: always
  volumes:
    - /var/www:/var/www/local.dev
    - /var/www/docker/php.ini:/usr/local/etc/php/php.ini
  links:
    - db:db

## Configuration PHP 7.2
php7.2:
  build: php7.2
  restart: always
  volumes:
    - /var/www:/var/www/local.dev
    - /var/www/docker/php.ini:/usr/local/etc/php/php.ini
  links:
    - db:db

## Configuration MySQL
db:
  image: mysql
  restart: always
  volumes:
    - /var/www/docker/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

## Configuration PhpMyAdmin
phpmyadmin:
  restart: always
  image: phpmyadmin/phpmyadmin
  environment:
    - MYSQL_ROOT_PASSWORD=root
  links:
    - db:db
  ports:
    - "3000:80"

## Configuration Maildev
maildev:
  restart: always
  image: djfarrelly/maildev
  ports:
    - "1080:80"
