## Configuration Nginx
web:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /var/www/docker/nginx:/etc/nginx/conf.d
    - /var/www:/var/www/local.dev
  links:
    - php7.1:php7.1
    - php7.2:php7.2
    - maildev:maildev
    - mysql:mysql
    - mongo:mongo
    - redis:redis
    - rethinkdb:rethinkdb

## Configuration PHP 7.1
php7.1:
  build: php7.1
  restart: always
  volumes:
    - /var/www:/var/www/local.dev
    - /var/www/docker/php.ini:/usr/local/etc/php/php.ini
  links:
    - mysql:mysql
    - mongo:mongo
    - redis:redis
    - rethinkdb:rethinkdb

## Configuration PHP 7.2
php7.2:
  build: php7.2
  restart: always
  volumes:
    - /var/www:/var/www/local.dev
    - /var/www/docker/php.ini:/usr/local/etc/php/php.ini
  links:
    - mysql:mysql
    - mongo:mongo
    - redis:redis
    - rethinkdb:rethinkdb

## Configuration MySQL
mysql:
  image: mysql
  restart: always
  volumes:
    - /var/www/docker/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - "3306:3306"

## Configuration Mongo
mongo:
  image: aashreys/mongo-auth:latest
  restart: always
  environment:
    - AUTH=yes
    - MONGODB_ADMIN_USER=admin
    - MONGODB_ADMIN_PASS=admin
    - MONGODB_APPLICATION_DATABASE=develop
    - MONGODB_APPLICATION_USER=test
    - MONGODB_APPLICATION_PASS=test
  volumes:
    - /var/www/docker/mongo:/data/db
  ports:
    - "27017:27017"

## Configuration Redis
redis:
  image: redis
  restart: always
  volumes:
    - /var/www/docker/redis.conf:/usr/local/etc/redis/redis.conf
    - /var/www/docker/redis/data:/data
  ports:
    - "6379:6379"

## Configuration RethinkDB
rethinkdb:
  image: rethinkdb
  restart: always
  volumes:
    - /var/www/docker/rethinkdb:/data
  ports:
    - "29015:29015"
    - "28015:28015"
    - "8000:8080"

## Configuration PhpMyAdmin
phpmyadmin:
  restart: always
  image: phpmyadmin/phpmyadmin
  environment:
    - MYSQL_ROOT_PASSWORD=root
  links:
    - mysql:db
  ports:
    - "3000:80"

## Configuration Maildev
maildev:
  restart: always
  image: djfarrelly/maildev
  ports:
    - "1080:80"
    - "1025:25"
